/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoreAvatarIndexRouteImport } from './routes/core/avatar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreAvatarIndexRoute = CoreAvatarIndexRouteImport.update({
  id: '/core/avatar/',
  path: '/core/avatar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/core/avatar/': typeof CoreAvatarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/core/avatar': typeof CoreAvatarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/core/avatar/': typeof CoreAvatarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/core/avatar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/core/avatar'
  id: '__root__' | '/' | '/core/avatar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreAvatarIndexRoute: typeof CoreAvatarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core/avatar/': {
      id: '/core/avatar/'
      path: '/core/avatar'
      fullPath: '/core/avatar/'
      preLoaderRoute: typeof CoreAvatarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreAvatarIndexRoute: CoreAvatarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
